### ISSUE TITLE
In Ie8 will has some problem.

### ISSUE THREAD

**Issue by FiShelly** [ovh-ux/rollup-plugin-less-inject#13]
Hello, when I run it in ie8, the program will get error.

I guess the `style inject function` has compatibility problems.

```
style.appendChild(document.createTextNode(css));   // ie8 not support
```

**Comment by frenautvh** [comment]
Hello, thanks for reporting this issue.
A PR has been opened : https://github.com/ovh-ux/rollup-plugin-less-inject/pull/14
